[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_files = [
    "README.md",
    "pyproject.toml",
]
version_scheme = "pep440"
version_provider = "uv"
major_version_zero = true
