name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: commitizen-tools/commitizen-action@0.24.0
        with:
          changelog_increment_filename: body.md
          git_redirect_stderr: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v2
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
          token: ${{ secrets.GITHUB_TOKEN }}
